-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    (SELECT AUTHOR_NAME FROM AUTHOR A WHERE B.AUTHOR_ID = A.AUTHOR_ID)
    AS AUTHOR_NAME,
    CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY 1, 3 DESC