-- 코드를 입력하세요
SELECT A.CART_ID
FROM
    (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Milk' GROUP BY CART_ID) A
    JOIN
    (SELECT * FROM CART_PRODUCTS WHERE NAME = 'Yogurt' GROUP BY CART_ID) B
    ON A.CART_ID = B.CART_ID
ORDER BY 1