-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (SUM(O.SALES_AMOUNT) * P.PRICE) AS PRICE
FROM PRODUCT P JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY PRICE DESC, P.PRODUCT_CODE ASC;
