-- 코드를 입력하세요
# 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회
# 결과는 보호 기간이 긴 순으로 조회
WITH TOTALDATE AS (
    SELECT
        I.ANIMAL_ID,
        DATEDIFF(O.DATETIME, I.DATETIME) + 1 AS TOTAL
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY TOTAL DESC
    LIMIT 2
)

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM TOTALDATE)