# -- 코드를 입력하세요
SELECT 
    P.PRODUCT_ID,
    PRODUCT_NAME,
    PRICE * (
    SELECT SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER O
    WHERE PRODUCE_DATE LIKE '2022-05%' AND O.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY O.PRODUCT_ID)
    AS TOTAL_SALES
FROM FOOD_PRODUCT P
WHERE P.PRODUCT_ID IN (SELECT DISTINCT O.PRODUCT_ID
                       FROM FOOD_ORDER O
                       WHERE PRODUCE_DATE LIKE '2022-05%')
ORDER BY 3 DESC, 1 ASC;
