WITH RENTAL_HISTORY AS (
    SELECT 
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DATE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
                THEN '90일 이상' 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
                THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
                THEN '7일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT 
    H.HISTORY_ID,
    CASE
        WHEN H.DURATION_TYPE IS NULL
            THEN FLOOR(H.RENTAL_DATE * C.DAILY_FEE)
        ELSE FLOOR(H.RENTAL_DATE * C.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100))
    END AS FEE
FROM RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON H.DURATION_TYPE = D.DURATION_TYPE AND D.CAR_TYPE = '트럭'
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC