-- 코드를 입력하세요
SELECT WRITER_ID AS USER_ID,
      (SELECT NICKNAME
       FROM USED_GOODS_USER
       WHERE WRITER_ID = USER_ID) AS NICKNAME,
       SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3;