-- 코드를 입력하세요
WITH MOST AS (
    SELECT COUNT(*), MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 1 DESC 
    LIMIT 1
)

SELECT
    P.MEMBER_NAME, 
    R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE P JOIN REST_REVIEW R
    ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID = (SELECT MEMBER_ID FROM MOST)
ORDER BY 3, 2