-- 코드를 작성해주세요
SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
WHERE LENGTH =
    (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = I.FISH_TYPE)