-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (FISH_INFO I JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE)
    JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEGTH
          FROM FISH_INFO
          GROUP BY FISH_TYPE) L
    ON N.FISH_TYPE = L.FISH_TYPE AND I.LENGTH = L.MAX_LEGTH