-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT)
    AS FILE_PATH
FROM USED_GOODS_FILE F
WHERE F.BOARD_ID = (SELECT B.BOARD_ID
                    FROM USED_GOODS_BOARD B
                    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD))
ORDER BY F.FILE_ID DESC

